### ISSUE TITLE
Fix Footer Icon Alignment on Mobile

### ISSUE THREAD

**Issue by jsontm** [ASU-CodeDevils/codedevils.org#26]
Footer Icons are not centered.

<img width="506" alt="Screen Shot 2023-05-02 at 3 06 24 PM" src="https://user-images.githubusercontent.com/34381646/235797774-a5575320-fcf5-4c23-9afa-520b49bbdf17.png">

**Comment by fernandonevarez** [comment]
refactored the navbar on mobile to look a lot different, the old design would have been best for an app. With some refactoring needing since the size of the navbar seemed a big bit for me looking back at it now.
<img width="344" alt="Screenshot 2023-07-12 at 11 30 28 PM" src="https://github.com/ASU-CodeDevils/codedevils/assets/69279785/4117e1f0-f109-406b-9aff-e91ebf0d1813">
<img width="346" alt="Screenshot 2023-07-12 at 11 31 15 PM" src="https://github.com/ASU-CodeDevils/codedevils/assets/69279785/c89441b3-24e3-41d7-94ef-807018592688">
