### ISSUE TITLE
Flatten and simplify the directory structure

### ISSUE THREAD

**Issue by jsontm** [ASU-CodeDevils/codedevils.org#41]
There are too many duplicate file names and unnecessarily nested dirs. For example there is a `components->headers->about.tsx` and a `pages->about.tsx`. Does this mean there is a separate About Header component that is only used one time and that's in the About Page - does it just add the specific text to the base header component?

<img width="228" alt="Screen Shot 2023-05-03 at 2 27 35 PM" src="https://user-images.githubusercontent.com/34381646/236054292-31aa5378-daa4-434e-9d48-e13631effe70.png">

**Comment by fernandonevarez** [comment]
So about that, the `pages->about.tsx` directory path nesting means that's the file path to the about page file. While the directory path `components->headers->about.tsx` is the file path to the about page's header file, since we have so many different variations of the header component. But I'll work on just having a single header component file that conditionally renders a given header based on which page you are on.

**Comment by fernandonevarez** [comment]
okay finished doing this.
