### ISSUE TITLE
Railway to Host Database Resources

### ISSUE THREAD

**Issue by IMBCIT** [ASU-CodeDevils/codedevils.org#5]
Investigate using Railway with Vercel to get database infra up and running with little to no overhead. 

[/integrations/railway](https://vercel.com/integrations/railway)

**Comment by IMBCIT** [comment]
Another service of interest is [PlanetScale](https://planetscale.com/)

**Comment by IMBCIT** [comment]
CockroachDB is another avenue to look into. Or we can just go with some AWS DB that could cause issues with Prisma and might not be worth the headaches and workarounds.

If we decided on AWS DB service a refactor of tech stack would be more beneficial.

**Comment by 0xfr4nkie** [comment]
I think this all comes down to whether we want to use SQL, NoSQL, or GraphQL. Some of the questions we need to ask to help us come to an answer might be: Does our data require strong relationships? What volume of data will we have to deal with? Will we need to scale our application? What types of data structures will our application be working with?

On the issue of hosting our database, since we are migrating to AWS, we can host SQL(MySQL, Postgres), NoSQL, and GraphQL through various services on AWS. However, we must consider how the cost will play into it and weigh the pros and cons of getting locked in by the vendor. I would say hosting NoSQL is cheaper/free most of the time.
